# Generated by Django 4.2.24 on 2026-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti_tool", "0007_lticontext_lti1p1_id_on_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ltideployment",
            name="pns_url",
            field=models.URLField(blank=True, verbose_name="PNS URL"),
        ),
        migrations.AddField(
            model_name="ltideployment",
            name="supports_asset_processor_submission_notice",
            field=models.BooleanField(
                default=False, verbose_name="supports Asset Processor Submission Notice"
            ),
        ),
        migrations.AddField(
            model_name="ltideployment",
            name="supports_context_copy_notice",
            field=models.BooleanField(
                default=False, verbose_name="supports Context Copy Notice"
            ),
        ),
    ]
